### ISSUE TITLE
Add an easier way to display formatted attributes (perhaps by adding another config entry)

### ISSUE THREAD

**Issue by cassie-jfs** [PlayerEXDirectorsCut/data-attributes#25]
### preface
The issue is currently, we are all over the place with how an attribute should be formatted.
The original DataAttributes had a `properties` section related to an attribute how it should be formatted, and some other things.

The benefits of this will allow us to pull from one source for our formatting in the manager and display the attribute correctly to the viewer.

There are two options:
- Attach to the `AttributeOverride` a `format` entry, which points to a way of formatting the `Double` attribute value (least cumbersome, seems preferrable, will bloat the class a bit).
- Make an entirely separate entry called `properties` (have to think of a higher purpose for it, will add another entry to the manager directly)

**Comment by DataEncoded** [comment]
FIXED IN #29 o7 o7 o7 o7 o7 o7 o7 o7 o7 tyfys
