### ISSUE TITLE
Just a quick question, when is the next release for fabric 1.20.1?

### ISSUE THREAD

**Issue by TheShadyyOneYT** [PlayerEXDirectorsCut/data-attributes#28]
We have all these beta and alpha releases, but yet, none of them are compatible with playerex other than the 1 release. Is there any chance in the near future (next 1-3 months) that we will have a stable release compatibility for fabric 1.20.1 other than version 1.6. For example will we have a version 2.0 that is a stable release compatible with PlayerEx?

**Comment by cassie-jfs** [comment]
Hi,

To answer your question briefly, I can not give an exact date for a fully stable release.


### A longer explanation~

PlayerEX and DataAttributes are honestly in a relatively completed state from its counterpart. All of the core features from the previous mod are now present, with just a few things to resolve, such as designing the UI as how the organizer intended, and formatting attributes correctly.

There are, on the PlayerEX Github, suggestions from the project organizer to incorporate three new features. These features add to the scope and time of the project.
I may consider making a plan to side-step the suggested features for now and establish a stable release once everything is in order, and then add the other content afterward in the next update(s) (though not set in stone yet).

Thank you for asking. I will leave this issue up for other questions until a stable release is done.

**Comment by TheShadyyOneYT** [comment]
Okay thank you! Glad to hear an update, I really do enjoy these mods and glad that it’s still getting updates. Good luck with the mod 🫡 excited to hear this news! 🙂

**Comment by cassie-jfs** [comment]
This has been completed. Documentation soon...

**Comment by TheShadyyOneYT** [comment]
sweet thanks
