### ISSUE TITLE
Can't set max level properly

### ISSUE THREAD

**Issue by PineTreePizza** [PlayerEXDirectorsCut/data-attributes#38]
I am using modrinth and made the datapack like the tutorial suggests after putting it in the datapacks folder it didn't seem to work, so I loaded it by opening the world datapacks and importing it but the max level is still 100, is there any way to set the max level to higher than 100? I'm talking about this level cap:
![image](https://github.com/user-attachments/assets/4e73691a-7e22-4473-997f-94c01465cdf0)

**Comment by cassie-jfs** [comment]
The wiki has some outdated information. It will be updated in due time.

There is a way to increase it higher than 100 though

**Comment by PineTreePizza** [comment]
> There is a way to increase it higher than 100 though

If you have any info on that I'd love to hear it. Thanks for the fast reply!

**Comment by cassie-jfs** [comment]
I'll have some info sent after I update PlayerEX to work with the release I just put out. Join the discord for the studio if you haven't by the way! I respond quicker there.

discord.gg/pcRw79hwey

**Comment by PineTreePizza** [comment]
> discord.gg/pcRw79hwey

This link doesn't seem to work unfortunately

**Comment by cassie-jfs** [comment]
It's odd because it is a valid link... but check the wiki again for data attributes, some things, especially with the config have been updated. Everything is not up to date though, it is still a work in progress.

https://bareminimumstudios.github.io/Bare-Minimum-Docs/data-attributes/datapack-setup/

This is a useful link~

**Comment by PineTreePizza** [comment]
> https://bareminimumstudios.github.io/Bare-Minimum-Docs/data-attributes/datapack-setup/
> This is a useful link~

Wow, thanks! That's exactly what I needed actually, now I can do everything I wanted. Closing the issue now, thanks a lot again.
