### ISSUE TITLE
[Bug] Data Attributes 2.0.0 causes spell cooldown to break completely [Fabric 1.20.1/0.16.5]

### ISSUE THREAD

**Issue by pokesmells** [PlayerEXDirectorsCut/data-attributes#39]
### What happened? Describe in detail down below and include the mod version as well.

https://github.com/user-attachments/assets/13e255ee-4d5f-43f7-bb7a-af0cd1549f9b

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [ ] Visual
- [X] Feature Related
- [ ] Crash
- [X] Mod Conflict
- [ ] Others

### Relevant logs

```shell
https://mclo.gs/X9iMbNp
```

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by cassie-jfs** [comment]
This has been fixed in PlayerEX (beta.8), just configured the haste incorrectly.
