### ISSUE TITLE
[Bug] Cannot Open Config when paired with 'Show me what you got!'

### ISSUE THREAD

**Issue by pokesmells** [PlayerEXDirectorsCut/data-attributes#42]
### What happened? Describe in detail down below and include the mod version as well.

Whenever I open up the config it errors out with this:

https://pokes-pics.has.rocks/Screenshot_2024-12-19_155701.png

This is the mod:
https://github.com/apace100/show-me-what-you-got

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [X] Visual
- [X] Feature Related
- [ ] Crash
- [X] Mod Conflict
- [X] Others

### Relevant logs

```shell
https://mclo.gs/WZ72y3S
```

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by DataEncoded** [comment]
fixed bossman
